upstream gunicorn_backend {
    server 127.0.0.1:5000;
    keepalive 100;
}
server {
    listen 80;
    server_name edu.ch-moltisanti.ru;
    server_tokens off;
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name edu.ch-moltisanti.ru;
    http2 on;

    ssl_certificate /etc/letsencrypt/live/edu.ch-moltisanti.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/edu.ch-moltisanti.ru/privkey.pem;

    client_max_body_size 20M;
    client_body_buffer_size 20M;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305";
    ssl_conf_command Ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256;
    ssl_prefer_server_ciphers on;
    ssl_ecdh_curve secp384r1;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    server_tokens off;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    location = /loaderio-59e49eb10c10d57d426716045012cbc5.txt {
        default_type text/plain;
        return 200 "loaderio-59e49eb10c10d57d426716045012cbc5";
    }
    location /static/ {
        alias /opt/eduonline/static/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
    location /uploads/ {
      alias /opt/eduonline/uploads/;
      expires 7d;
      add_header Cache-Control "public, no-transform";
    }
    location / {
        proxy_pass http://gunicorn_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}